# Generated by Django 4.2.23 on 2025-07-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('Residencial', 'residencial'), ('Comercial', 'comercial')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_cuartos', models.IntegerField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='app.edificio')),
            ],
        ),
    ]
